import { activeItems, BUDGET, grandTotal, itemTotal, money } from '../model'
import type { Requisition } from '../model'
import { Icon } from './Icon'

export function Review({ value, onRemark, onBack, onSubmit, onPreview, busy }: { value: Requisition; onRemark: (text: string) => void; onBack: () => void; onSubmit: () => void; onPreview: () => void; busy: boolean }) {
  const total = grandTotal(value.items), remaining = BUDGET - total
  return <div className="review-grid"><section className="budget-panel bordered-panel"><table className="budget-table"><caption>Budget Control Sheet</caption><tbody>
    <tr><th>Budget Type</th><td colSpan={3}>{value.basic.budgetType}</td></tr><tr><th>Budget Year</th><td colSpan={3} className="number">{new Date(value.createdAt).getFullYear()}</td></tr><tr><th>Budget Status</th><td colSpan={3} className="number">{remaining >= 0 ? 'ON BUDGET' : 'OVER BUDGET'}</td></tr><tr><th>Cost Center</th><td colSpan={3} className="number">TECHNOLOGY DEVELOPMENT</td></tr>
    <tr><th rowSpan={3}>PR</th><th rowSpan={2}>Waiting for PO.</th><th>PR. Pending (B)</th><td className="number">0.00 B</td></tr><tr><th>PR. Approve (C)</th><td className="number">0.00 B</td></tr><tr><th colSpan={2}>Amount of “This order” (D)</th><td className="number">{money(total)} B</td></tr>
    <tr><th rowSpan={2}>Main</th><th>Budget Code</th><td colSpan={2} className="number budget-code">{value.basic.budgetCode}</td></tr><tr><th>Budget Amount (A)</th><td colSpan={2} className="number">{money(BUDGET)} B</td></tr>
    <tr><th rowSpan={2}>Sub</th><th>Budget Code</th><td colSpan={2}>—</td></tr><tr><th>Budget Amount</th><td colSpan={2}>—</td></tr>
    <tr className="budget-footer"><th colSpan={3}>Latest accumulate PO. issue (E)</th><td className="number">0.00 B</td></tr><tr className="budget-remain"><th>Budget Remain</th><td colSpan={2}>F = A - (B+C+D+E)</td><td className="number">{money(remaining)} B</td></tr>
  </tbody></table><label className="remark-field review-remark"><span>Remark / หมายเหตุ</span><textarea placeholder="Write your remark . . . ." value={value.remark} onChange={e => onRemark(e.target.value)} /></label>
  </section><div><section className="summary-panel bordered-panel"><h2>PR &amp; Budget Summary</h2><div className={`budget-badge ${remaining < 0 ? 'over-budget' : ''}`}><img src={`${import.meta.env.BASE_URL}figma/budget-check.svg`} alt="" /><div>{remaining >= 0 ? 'ON BUDGET' : 'OVER BUDGET'}<small>{remaining >= 0 ? 'วงเงินเพียงพอ' : 'วงเงินไม่เพียงพอ'}</small></div></div><div className="summary-total"><h3>Grand Total / ยอดรวมสุทธิ</h3><p><strong>{money(total)}</strong> THB</p></div>
    <dl className="budget-numbers"><div><dt>Budget Amount (A)</dt><dd>{money(BUDGET)} THB</dd></div><div><dt>This Order (D)</dt><dd>{money(total)} THB</dd></div><div><dt>Budget Remain (F)</dt><dd>{money(remaining)} THB</dd></div></dl>
    <dl className="pr-summary"><div><dt>PR No.</dt><dd>{value.reference || '-'}</dd></div><div><dt>Require Date</dt><dd>{value.basic.requiredDate.split('-').reverse().join('/')}</dd></div><div><dt>Department</dt><dd>Technology Development</dd></div><div><dt>Cost Center</dt><dd>26-23-ADM-088</dd></div><div><dt>Requester</dt><dd>Worawut Jintasri</dd></div></dl>
    <div className="tip"><strong>ⓘ Tip / คำแนะนำ</strong><p>กรุณาตรวจสอบรายการสินค้าและเอกสารแนบให้ครบถ้วน ก่อนกด Submit</p></div>
    <details className="review-details"><summary>Items &amp; attachments ({activeItems(value.items).length} / {value.attachments.length})</summary><ul>{activeItems(value.items).map(item => <li key={item.id}>{item.name} × {item.quantity} · {money(itemTotal(item))} THB</li>)}</ul><ul>{value.attachments.map(attachment => <li key={attachment.id}>{attachment.file.name}</li>)}</ul><p>{value.purchaser}</p></details>
  </section><div className="step-actions"><button type="button" className="button secondary" onClick={onBack}>Back</button><button type="button" className="button primary" disabled={busy} onClick={onSubmit}><Icon name="send" />{busy ? 'Submitting…' : 'Submit'}</button></div><button type="button" className="button pdf-button" onClick={onPreview}><Icon name="file" />View PDF</button></div></div>
}

export function PrintableRequisition({ value }: { value: Requisition }) {
  return <article className="print-document"><header><p>COMPANY LIMITED · PROCUREMENT</p><h1>Purchase Requisition / ใบขอสั่งซื้อ</h1><p>{value.reference || 'DRAFT'} · {new Date(value.createdAt).toLocaleDateString('en-GB')}</p></header><dl><div><dt>Requester</dt><dd>Worawut Jintasri</dd></div>{Object.entries(value.basic).map(([key, text]) => <div key={key}><dt>{({ job: 'Jobs Name', mainGroup: 'Main Group', budgetType: 'Budget Type', requiredDate: 'Require Date', budgetCode: 'Budget Code', purpose: 'Purpose', line: 'Line', description: 'Budget Description', currency: 'Currency' } as Record<string, string>)[key]}</dt><dd>{text || '—'}</dd></div>)}</dl><table><thead><tr><th>No.</th><th>Item / รายการ</th><th>QTY</th><th>Unit</th><th>Unit Price</th><th>Total (THB)</th></tr></thead><tbody>{activeItems(value.items).map((item, index) => <tr key={item.id}><td>{index + 1}</td><td>{item.name}<small>{[item.brand, item.model, item.detail].filter(Boolean).join(' · ')}</small></td><td>{item.quantity}</td><td>{item.unit}</td><td>{money(Number(item.price))}</td><td>{money(itemTotal(item))}</td></tr>)}</tbody><tfoot><tr><th colSpan={5}>Grand Total / ยอดรวมสุทธิ</th><td>{money(grandTotal(value.items))}</td></tr></tfoot></table><h3>Remark / หมายเหตุ</h3><p>{value.remark || '—'}</p><h3>Attachments / เอกสารแนบ</h3><ul>{value.attachments.map(a => <li key={a.id}>{a.file.name}</li>)}</ul><p>Purchaser: {value.purchaser || '—'}</p><footer>Local prototype · This document has not been sent for approval.</footer></article>
}
