const assert = require('node:assert/strict')
const path = require('node:path')
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')

async function main() {
  const browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}) })
  try {
    const context = await browser.newContext({ baseURL: process.env.APP_URL || 'http://127.0.0.1:5173', viewport: { width: 1440, height: 1024 } })
    await context.addInitScript(() => sessionStorage.setItem('sa-pr-session', JSON.stringify({ token: 'test', employee: { employee_id: 'E0020', full_name: 'Test User', position: 'Employee', department: 'IT', approval_level_id: null } })))
    await context.route('**/api/**', route => route.fulfill({ contentType: 'application/json', body: JSON.stringify({ data: [], pagination: { total: 0, total_pages: 1, page: 1, limit: 100 } }) }))
    const page = await context.newPage()
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto('/')
    await page.getByRole('button', { name: 'สร้างคำขอ', exact: true }).click()
    const input = page.getByLabel('Require Date/วันที่ต้องการของ', { exact: true })
    const trigger = page.getByRole('button', { name: 'Choose required date', exact: true })
    const calendar = page.getByRole('dialog', { name: 'Choose required date', exact: true })
    await input.fill('2026-10-04')
    await trigger.click()
    await calendar.waitFor()
    assert.equal(await calendar.getByRole('button', { name: 'Sunday, October 4, 2026', exact: true }).getAttribute('aria-pressed'), 'true')
    await calendar.evaluate(async element => { await Promise.all(element.getAnimations().map(animation => animation.finished)) })
    await page.screenshot({ path: path.join(require('node:os').tmpdir(), 'pr-calendar-desktop.png') })
    await calendar.getByRole('button', { name: 'Next month', exact: true }).click()
    assert.match(await calendar.locator('header strong').innerText(), /November 2026/)
    await calendar.getByRole('button', { name: 'Previous month', exact: true }).click()
    await calendar.getByRole('button', { name: 'Friday, October 30, 2026', exact: true }).click()
    assert.equal(await input.inputValue(), '2026-10-30')
    assert.equal(await calendar.count(), 0)
    await input.fill('2026-10-31')
    await trigger.click()
    await page.keyboard.press('ArrowRight')
    assert.match(await calendar.locator('header strong').innerText(), /November 2026/)
    await page.keyboard.press('Enter')
    assert.equal(await input.inputValue(), '2026-11-01')
    await input.fill('2028-02-29')
    await trigger.click()
    await page.keyboard.press('PageDown')
    await page.keyboard.press('Enter')
    assert.equal(await input.inputValue(), '2028-03-29')
    await trigger.click()
    await page.keyboard.press('Escape')
    assert.equal(await calendar.count(), 0)
    assert.equal(await trigger.evaluate(element => element === document.activeElement), true)
    await trigger.click()
    await calendar.getByRole('button', { name: 'Clear / ล้าง', exact: true }).click()
    assert.equal(await input.inputValue(), '')
    assert.equal(await input.evaluate(element => element.checkValidity()), false)
    await trigger.click()
    await calendar.getByRole('button', { name: 'Today / วันนี้', exact: true }).click()
    const today = await page.evaluate(() => { const date = new Date(); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}` })
    assert.equal(await input.inputValue(), today)
    await trigger.click()
    await page.getByLabel('Jobs Name/ชื่องาน', { exact: true }).click()
    assert.equal(await calendar.count(), 0)
    await page.setViewportSize({ width: 390, height: 844 })
    await trigger.click()
    await calendar.waitFor()
    const rect = await calendar.boundingBox()
    assert.ok(rect.x >= 0 && rect.x + rect.width <= 390 && rect.y >= 0 && rect.y + rect.height <= 844, 'Calendar is outside the mobile viewport')
    await calendar.evaluate(async element => { await Promise.all(element.getAnimations().map(animation => animation.finished)) })
    await page.screenshot({ path: path.join(require('node:os').tmpdir(), 'pr-calendar-mobile.png') })
    await page.emulateMedia({ reducedMotion: 'reduce' })
    assert.equal(await calendar.evaluate(element => getComputedStyle(element).animationName), 'none')
    assert.deepEqual(errors, [])
    await context.close()
    console.log('PASS styled date picker: selection, typed dates, month navigation, keyboard navigation across months, leap year, Escape, Today, Clear, required validation, outside click, mobile fit and reduced motion')
  } finally { await browser.close() }
}
main().catch(error => { console.error(error); process.exitCode = 1 })
